### ISSUE TITLE
Shadowbox shows only pictures of one page of the album

### ISSUE THREAD

**Issue by DenisMuc** [andrewhoule/silverstripe-photogallery#13]
The shadowbox-function works fine when I click on a picture. But it is only possible to go through the pictures that are on the page where I am right now. How is it possible to go through all pictures of one album in the shadowbox? Thank you

**Comment by andrewhoule** [comment]
Do you mean if the images in a gallery are split because of pagination? If so, you can increase the items per page on the config tab, but it won't work across pages.

**Comment by andrewhoule** [comment]
Switched to magnific popup
