### ISSUE TITLE
Dataextension doesn't work well

### ISSUE THREAD

**Issue by brasileric** [andrewhoule/silverstripe-photogallery#4]
I want to add extra fields to PhotoItem dataobject by using dataextension. Below is my code, the extra fieds has been added to the database table, but in the cms the form fields doesn't appaer. Any idea what can be the cause? I added the dataextension to my config.yml as well and did /dev/build?flush=all

<?php

class CustomPhotoItem extends DataExtension {
	
	private static $db = array (
		'CaptionEn' => 'Text',
		'CaptionDe' => 'Text'
	);
	
	private static $has_one = array (
	);

    public function updateCMSFields(FieldList $fields) {
        //$fields->addFieldToTab('Root.Main', new TextField('CaptionEn', 'Extra Text Field'),'Caption');
        $fields->push(new TextField('CaptionEn'));
        $fields->push(new TextField('CaptionDe'));

    }

}

**Comment by camfindlay** [comment]
Looks like this is resolved in #3 perhaps close out this issue :D
