### ISSUE TITLE
Photo album split into separate images/thumbnail images only

### ISSUE THREAD

**Issue by mhenden** [andrewhoule/silverstripe-photogallery#6]
Can't understand what's happening here. Module installed simply enough -- CMS interface works really well -- nice job Andrew! Uploaded three photo albums which worked as expected, then tried to add more images to the first gallery, which gave me two more photo albums on the same page. Trashed the gallery and uploaded image folder and tried to drop all the images in to a single new photo album. Instead it gave me an individual album for each image, along with a reduced thumbnail image. What's going on here?!!

**Comment by mhenden** [comment]
Just trashed it all again, even changed the name of the gallery. Same result. What gives? What gives, what gives, what gives?

**Comment by andrewhoule** [comment]
Check the options in 'Config' tab, they may be helpful for what you are trying to do. In there you can set the size of the thumbs for the albums and the photos themselves (of course CSS is a good way to refine this, especially with a responsive site). You can also default to showing the album even if it has no images, or hide it if it's empty.

I'm a bit confused what you are trying to do... So after experimenting with the options in config if you are still not getting the results you'd like feel free to get back to me.

**Comment by mhenden** [comment]
Hi Andrew

Thanks for getting back to me. 

I’ve taken a look at the Config tab — once again very well thought out, but in this case it makes no difference. All three pages have default settings. 

I’m trying to have three separate photo albums on three separate pages (Domestic, Commercial and Showroom). On Commercial and Showroom (which have under 20 images each) I get all the images for these pages appearing on the page, which is what I want. 

When I first uploaded the Domestic images I had a single gallery of 25 images. I then found more images (four, then another three) which I uploaded. These appeared as separate albums beneath the initial images. 

So I dumped the gallery and tried to upload all 32 images onto the Domestic page at once. Result: 32 individual galleries!! 

I just dumped the whole page, set up a new page and tried again, with the same result. 

Why is this page behaving differently when settings are the same? It’s almost as if it’s a cache problem that won’t go away?!

cheers
MIKE




	14 Brees Street, Lower Hutt, Wellington, New Zealand
p: 04-577 0243, m: 027 4419 273, e: mike@mhdesign.co.nz
w: www.mhdesign.co.nz

**Comment by andrewhoule** [comment]
Strange. I can't replicate the issue in a test environment with the newest version of SilverStripe and the module. Could you email me directly at andrewhoule@gmail.com and send the example page and an SS login to check it out?

**Comment by andrewhoule** [comment]
Hey Mike, I'm going to close this out now. If you are still running into this issue, please open this back up.

**Comment by mhenden** [comment]
All good thanks Andrew. Thanks for a great package — and ‘have a Cool Yule’! 

cheers
MIKE




	14 Brees Street, Lower Hutt, Wellington, New Zealand
p: 04-577 0243, m: 027 4419 273, e: mike@mhdesign.co.nz
w: www.mhdesign.co.nz
