### ISSUE TITLE
Responsive view of lightbox issues (smartphone)

### ISSUE THREAD

**Issue by mhenden** [andrewhoule/silverstripe-photogallery#8]
Hi Andrew, having a problem with lightbox function on smartphone. Image opens at full size (700 x 700px) and I am unable to navigate around the enlarged images. I'm also unable to close image without refreshing the screen. Have you struck this problem? 
cheers, Mike

**Comment by mhenden** [comment]
OK, I sussed it -- needed to add an extra rule to shadowbox.css but I'm not sure how to contribute?

**Comment by andrewhoule** [comment]
Yeah, I've been meaning to switch out the lightbox for so long now. Shadowbox was fine at the time, but I'm not sure it's got the best license for an open source module, and it's not very responsive. I'm leaning toward switching to something like this - https://github.com/brutaldesign/swipebox 

Hopefully this pushes me to make that update, but if you're feeling keen to contribute (and that would be awesome!). You could switch that out and put in a pull request.

**Comment by mhenden** [comment]
Hi Andrew

Happy to switch out code to make lightbox responsive but I’m not sure how I would go about this. Can you please clarify? 

cheers
MIKE




	14 Brees Street, Lower Hutt, Wellington, New Zealand
p: 04-577 0243, m: 027 4419 273, e: mike@mhdesign.co.nz
w: www.mhdesign.co.nz

**Comment by andrewhoule** [comment]
You can fork the code make your updates and submit a pull request so I can review and potentially merge it into the master branch. Here's the docs for that - https://help.github.com/articles/using-pull-requests/

No worries if you don't have the time. Just a bonus if you do ;)

**Comment by PsukheDelos** [comment]
Hi @andrewhoule 

Just going to tack onto this conversation as you mentioned ShadowBox's license.  The latest version of ShadowBox actually has a new GNU (:P) license that might interest you.  Not sure if it solves the responsive issue or not, but just thought I'd let you know.  You can check it out [here](https://github.com/mjackson/shadowbox).  Hope this helps!  :)  

Glen

**Comment by andrewhoule** [comment]
Oh, good deal! I still want to switch that out (for the sake of being responsive). Thanks.

**Comment by mhenden** [comment]
Hi Andrew, you got me on 'submit a pull request' -- I thought I'd sorted this but found the same error on another one of my sites. Reviewed things and discovered how I fixed it last year. Tried the 'pull request' but can't find my way around Git (don't use it much and should know it better but... 

So here's the stylesheet. The last rule is the one that fixes it. Hope this helps! 

[shadowbox.css.zip](https://github.com/andrewhoule/silverstripe-photogallery/files/145895/shadowbox.css.zip)

**Comment by andrewhoule** [comment]
Hey Mike, Thanks for sharing that! I've let this module gather too much dust... I think this is the new lightbox I'm going to settle on - http://photoswipe.com/ It's an MIT license and has great mobile support baked in (e.g. responsive and touch controls). But until then, this is great to have that css here for anyone who is interested.
